Rails:
  Enabled: true
AllCops:
  Include:
    - Rakefile
    - config.ru
    - lib/**/*.rake
  Exclude:
    - app/controllers
    - bin/setup
    - config/initializers/**
    - config/spring.rb
    - config/environments/development.rb
    - db/schema.rb
    - db/migrate/**/*
    - spec/factories/**/*
    - Gemfile

Metrics/BlockLength:
  Max: 90
  Exclude:
    - "**/*_spec.rb"
Metrics/ModuleLength:
  Exclude:
    - "**/*_spec.rb"
Metrics/LineLength:
  Enabled: false
Style/StringLiterals:
  Enabled: false
Layout/EndOfLine:
  Enabled: false
Documentation:
  Enabled: false
